/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.mafer.calculadora.gui;

import me.mafer.calculadora.TipoOperacao;
import java.awt.Color;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author fefe
 */
public class FrameCalculadora extends javax.swing.JFrame {
    
    public void atualizarLabelExibicao(String calculo) {
        labelExibicao.setText(calculo);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameCalculadora.class.getName());

    /**
     * Creates new form FrameCalculadora
     */
    public FrameCalculadora() {
        initComponents();
        
        this.getContentPane().setBackground(new Color(24, 20, 20));
        PainelExibicao.setBackground(new Color(40, 36, 36));
        PainelExibicao.setBorder(new EmptyBorder(5, 5, 5, 5));
        painelBotoes.setBackground(new Color(24, 20, 20));
        
        labelExibicao.setForeground(new java.awt.Color(255, 255, 255));
        
        BotaoCalculadora.labelExibicao = labelExibicao;
        
        BotaoCalculadora botaoSETE = new BotaoCalculadora("7", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoOITO = new BotaoCalculadora("8", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoNOVE = new BotaoCalculadora("9", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoMAIS = new BotaoCalculadora("+", TipoOperacao.OPERADOR, 1);
        BotaoCalculadora botaoQUATRO = new BotaoCalculadora("4", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoCINCO = new BotaoCalculadora("5", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoSEIS = new BotaoCalculadora("6", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoMENOS = new BotaoCalculadora("-", TipoOperacao.OPERADOR, 1);
        BotaoCalculadora botaoUM = new BotaoCalculadora("1", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoDOIS = new BotaoCalculadora("2", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoTRES = new BotaoCalculadora("3", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoVEZES = new BotaoCalculadora("x", TipoOperacao.OPERADOR, 2);
        BotaoCalculadora botaoZERO = new BotaoCalculadora("0", TipoOperacao.OPERANDO, 0);
        BotaoCalculadora botaoIGUAL = new BotaoCalculadora("=", TipoOperacao.CALCULAR, 0);
        BotaoCalculadora botaoRESET = new BotaoCalculadora("C", TipoOperacao.RESET, 0);
        BotaoCalculadora botaoDIVIDIR = new BotaoCalculadora("/", TipoOperacao.OPERADOR, 2);
        painelBotoes.add(botaoSETE);
        painelBotoes.add(botaoOITO);
        painelBotoes.add(botaoNOVE);
        painelBotoes.add(botaoMAIS);
        painelBotoes.add(botaoQUATRO);
        painelBotoes.add(botaoCINCO);
        painelBotoes.add(botaoSEIS);
        painelBotoes.add(botaoMENOS);
        painelBotoes.add(botaoUM);
        painelBotoes.add(botaoDOIS);
        painelBotoes.add(botaoTRES);
        painelBotoes.add(botaoVEZES);
        painelBotoes.add(botaoZERO);
        painelBotoes.add(botaoIGUAL);
        painelBotoes.add(botaoRESET);
        painelBotoes.add(botaoDIVIDIR);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelExibicao = new javax.swing.JPanel();
        labelExibicao = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelExibicao.setText("0");

        javax.swing.GroupLayout PainelExibicaoLayout = new javax.swing.GroupLayout(PainelExibicao);
        PainelExibicao.setLayout(PainelExibicaoLayout);
        PainelExibicaoLayout.setHorizontalGroup(
            PainelExibicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelExibicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelExibicao)
                .addContainerGap())
        );
        PainelExibicaoLayout.setVerticalGroup(
            PainelExibicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelExibicaoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelExibicao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBotoes.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PainelExibicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(PainelExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelExibicao;
    private javax.swing.JLabel labelExibicao;
    private javax.swing.JPanel painelBotoes;
    // End of variables declaration//GEN-END:variables
}
